# Assignment 1

# Introduction:
PyTorch is library in the python that provides maximum fexibility and speed and is well known for its fast computational power. It is similar to numpy but this contains power of GPU.

In [0]:
# Import torch and other required modules
import torch

I am going to impliment 5 funtions of pytorch:


1.   floor_divide(value)

floor_divide is a function in the pytroch which gives us the lowest integer in the division part. that is if our division result would be either 2.03 or 1.98 then our floor_divide gives the result 2 and 1 respectively.

In [0]:
#1 floor_division
a = torch.tensor([4.0, 8.0,8.0])
b = torch.tensor([2.0, 2.0,6.0])
c=torch.floor_divide(a, b)



In [3]:
torch.floor_divide(a,1.8)

tensor([2., 4., 4.])

this frac function gives the fractional part in the decimal number.

In [4]:
torch.frac(torch.div(a,b))

tensor([0.0000, 0.0000, 0.3333])

2. torch.argsort(vales)
This function gives the output of the values in sorted form. The default output will be in the ascending order by value.

In [27]:
a = torch.randn(3, 4)
print(a)
torch.argsort(a)

tensor([[-0.0442, -0.2813, -1.0147,  0.9906],
        [ 1.0399,  0.3348,  0.2659,  1.8946],
        [ 0.2963,  0.1490,  0.2883,  0.8292]])


tensor([[2, 1, 0, 3],
        [2, 1, 0, 3],
        [1, 2, 0, 3]])

3. torch.equal(input). 

This function gives boolean output and it compares the values in side the input.

In [28]:
torch.equal(torch.tensor([2,2,1]), torch.tensor([1, 2]))

False

4. torch.isnan()

This function gives the missing values are present in the the data or not? But it gives the boolean output.

In [30]:
torch.isnan(torch.tensor([float('nan'), float('nan'), 5,2]))

tensor([ True,  True, False, False])

from above output we can see that 'nan' value means and it compare and gives the output is True because we are comparing the missing values so it says that yes.

5. torch.max()

This function gives the maximum values present in the data.

In [33]:
a=torch.randn(3,4)
print(a)
torch.max(a)

tensor([[-0.4106, -1.0540,  1.6819,  0.2485],
        [-0.4715,  2.0338, -1.1480, -1.4665],
        [-0.5358,  1.6344, -0.6077,  0.5214]])


tensor(2.0338)